### ISSUE TITLE
Ongoing wine-tkg-git issue: Build fails after commit 1e7c6d7 (2022-05-25)

### ISSUE THREAD

**Issue by Nolij** [NyanCatTW1/robloxWineBuildGuide#18]
Following the instructions exactly I get this error when attempting to build:
```
In file included from /usr/include/X11/Xlib.h:44,
                 from ../wine-mirror-git/dlls/winex11.drv/systray.c:31:
../wine-mirror-git/include/processthreadsapi.h:43:11: error: expected identifier or ‘(’ before numeric constant
   43 |     ULONG ControlMask;
      |           ^~~~~~~~~~~
```

This happens in multiple places. I've tried a clean build. I've updated my packages. I've built successfully in the past. Distro is Arch Linux (not an "i use arch btw" I mention for context about build dependency versions).

**Comment by rolexlinux** [comment]
Same here `kernel 5.18.0-arch1-1` (fresh build)

**Comment by rolexlinux** [comment]
This seems to fail the build on normal wine-tkg-git without any patches.

**Comment by rolexlinux** [comment]
I have made an issue on the repo now.
https://github.com/doitsujin/dxvk/issues/2657

**Comment by e666666** [comment]
This seems like a tough one...I'll try to build it myself and see if I could reproduce the issue.
Updates will be edited onto this comment.

**Comment by Nolij** [comment]
> This seems like a tough one...I'll try to build it myself and see if I could reproduce the issue.
> 
> Update 1: Found upstream issue: [Frogging-Family/wine-tkg-git#779](https://github.com/Frogging-Family/wine-tkg-git/issues/779) wine-tkg-git builds appear to not work currently ...Wait, rolexlinux found this issue already, ¯\_(ツ)_/¯
> 
> Update 2: Reproduced the error on default config, rebuilding without staging... Update 3: Reproduced the error on Mainline master, trying wine-7.8 branch...

7.7 was even failing for me, not sure 7.8 will be any better

**Comment by NyanCatTW1** [comment]
You happen to be online? Nice! Let's meet on #wine Grapejuice

**Comment by Nolij** [comment]
xdMatthewbx#1337

**Comment by NyanCatTW1** [comment]
The faulty commit is https://github.com/wine-mirror/wine/commit/1e7c6d73c8f558668c6140d4a97fae0ad51d71eb

**Comment by NyanCatTW1** [comment]
Further update & workarounds can be found in upstream https://github.com/Frogging-Family/wine-tkg-git/issues/779 , this issue will stay open until upstream fixes the issue.

**Comment by NyanCatTW1** [comment]
Fixed in upstream: https://github.com/Frogging-Family/wine-tkg-git/commit/134bc9bda15fce13c378af3d5e6e35d629664a56
The fix was practically identical to my workaround, just implemented differently ¯\_(ツ)_/¯

Closing issue.
